name: minishell - CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Rebuild
        run: make re
      - name: Test lexical analysis
        run: gcc -g -I inc -L./libft -lft src/test.c src/lex.c libft/libft.a && ./a.out > test_out.txt
      - name: Compare output files
        run: diff -q test_out.txt correct_out.txt
      - name: Clean
        run: make fclean && rm -f a.out test_out.txt
